Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Editor/Resources/BMS_Forge_Editor/NetworkObjectTemplate.txt

When transferring ownership, the base `NetworkObject` class wasn't being called here. This was preventing the `ownershipChanged` event from firing on the server. Calling the base class results in `ownershipChanged` being properly fired, as expected.

NetworkObjects call base class when ownership changes

---

BeardedManStudios/Source/SimpleJSON.cs
ForgeNetworkingCommon/Templating/TemplateSystem.cs
ForgeNetworkingUnityEditor/ForgeNetworkingUnityEditor.csproj
ForgeNetworkingUnityEditor/SimpleJSONEditor.cs
UnitTests/Source/UnityEditor/JSONNodeTests.cs
UnitTests/UnitTests.csproj

Added some ToString formatting specificators on float handling to support culture-specific decimal separator. Included some very basic unit tests for main parsing part, didn't add tests for generator parts.
Also made the Unity assembly references to be relative on ForgeNetworkingUnityEditor project, as it failed to get the Unity-created references.

Fixed float parsing/generating with non-dot decimal separator

---

BeardedManStudios/Source/BMSByte.cs
BeardedManStudios/Source/Forge/Networking/NetWorker.cs
BeardedManStudios/Source/Forge/Networking/NetworkingPlayer.cs
Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Editor/Resources/BMS_Forge_Editor/NetworkManagerTemplate.txt
Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Scripts/Multiplayer Menu/MultiplayerMenu.cs
Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Scripts/NetworkManager.cs

- Removed 'static' from BMSByte allowedTypes dictionary, so it will not collide with other Threads
- Added an ability to set firewall port on PingForFirewall() method (prevent collisions between two Networkers on connection stage)
- Fixed a bug of LINQ usage in reliableComposers (raised freezes sometimes on huge UDP stream)
- Added a check of Networker to NetworkManagerTemplate.txt, because it can be already removed on NetworkManager Destroy
- Uncommented check of loadedScenes.Count which raised an error if no loadedScenes used

Some fixes (critical and not)

---

Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Scripts/NetworkBehavior.cs

This seems to have fixed the issue with not being able to call RPCs from the `networkStarted` event.  I haven't tested it thoroughly, but it seems to be working so far.

Call "CompleteRegistration()" before "networkStarted(this)"

---

Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Scripts/Server Browser/ServerBrowser.cs

For iOS and Android TCPClientWebsockets aren't needed and cause the build to fail.
Removing them through Unity preprocessing conditionals resolve the build issue on the mobile platforms

Exclude TCPClientWebsockets on mobile builds

---

docs/mkdocs/docs/GettingStarted/basic-instantiation-example.md
docs/mkdocs/docs/GettingStarted/jump-start-guide.md

This pull request updates the tutorial documentation for the basic instantiation example and the jump start guide by replacing the now obsolete NetworkManager.Instance.InstantiateMyClassNetworkObject with NetworkManager.Instance.InstantiateMyClass, and by unifying the way the code accesses a Collider's attached component (in this case, the Player object).
These were minor inconsistencies that jumped out at me while I was going through the material, and prompted by other users, I thought I would try and fix it.

Update obsolete methods and inconsistencies in tutorial documentation

---

BeardedManStudios/Source/Forge/Networking/TCPClientBase.cs
Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Scripts/NetworkManager.cs
MasterServer/Program.cs

Crash occurs few seconds after hitting Stop button.
Those two changes fix the same issue so only one of them is needed. Not sure which one is better.

Fixed unity crash when connection to master server failed

---

Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Editor/Resources/BMS_Forge_Editor/NetworkBehaviorTemplate.txt

Related to issue #66 
`transform.position` was being set after `NetworkStart()` was called, so getting or setting `transform.position` in `NetworkStart()` could result in unexpected behavior depending on the situation.
This simply just moves the line that calls `NetworkStart()` below the lines that set the `transform.position`.
NCW will need to be saved in order to re-generate everything to see any changes.

Call NetworkStart() after setting position

---

BeardedManStudios/Source/Forge/DataStore/Cache.cs
BeardedManStudios/Source/Forge/Networking/ObjectMapper.cs
BeardedManStudios/Source/Forge/Networking/Objects/NetworkObject.cs
Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Scripts/NetworkManager.cs
UnitTests/Source/FrameTests.cs
UnitTests/Source/UDP/ReliablePacketTests.cs

Instead of:
BMSByte data = new BMSByte();
ObjectMapper.Instance.MapBytes(data, obejct[] args);
It's just:
BMSByte data = ObjectMapper.BMSByte(obejct[] args);

Shortcut for quick BMSByte creation

---

BeardedManStudios/Source/Forge/DataStore/Cache.cs
BeardedManStudios/Source/Forge/Networking/ObjectMapper.cs
BeardedManStudios/Source/Forge/Networking/Objects/NetworkObject.cs
BeardedManStudios/Source/Forge/Networking/TCPClientBase.cs
BeardedManStudios/Source/Forge/Networking/TCPServer.cs
BeardedManStudios/Source/Forge/Networking/UDPClient.cs
BeardedManStudios/Source/Forge/Networking/UDPServer.cs
Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Scripts/NetworkManager.cs
UnitTests/Source/FrameTests.cs
UnitTests/Source/UDP/ReliablePacketTests.cs

[enhancement issue](https://github.com/BeardedManStudios/ForgeNetworkingRemastered/issues/27)
Those also resolve issue of remembering that TCPServer sends not masked streams, TCPClient masked streams etc.
I was confused at start searching why TCPServer doesnt receive not masked packets
Example:
Before:
```
BMSByte data = new BMSByte();
ObjectMapper.Instance.MapBytes(data, playerHostAddress);
Binary frame = new Binary(server.Time.Timestep, false,
data, Receivers.Target, QUEUE_SERVER_HOST_GAME, true);
server.Send(playerHost.TcpClientHandle, frame);
```
After:
```
server.Send(playerHost.TcpClientHandle, Receivers.Target, 
QUEUE_SERVER_HOST_GAME, playerHostAddress);
```

Shortcuts to send packets

---

BeardedManStudios/Source/BMSByte.cs
BeardedManStudios/Source/Forge/Networking/ObjectMapper.cs
BeardedManStudios/Source/Forge/Networking/Objects/NetworkObject.cs
UnitTests/Source/BMSByteTests.cs
UnitTests/Source/ObjectMapperTests.cs

Instead of mapping/appending every object to a BMSByte (which causes a lot of Resize calls):
1. All of them are converted to byte[] using GetBytesArray
2. Then they are stored in byte[][]
3. Then whole byte[][] is appended to BMSByte which resize only once
+-20% faster depending how much objects are added at once

Optimization of multiple objects serialization

---

docs/mkdocs/docs/GettingStarted/basic-instantiation-example.md
docs/mkdocs/docs/GettingStarted/basic-moving-cube-example.md

Hi,
a few tiny corrections in docs:
- remove mistyped character
- fix movement vector axes - movement in Unity is on `z` axis, not `y`
- normalize movement vector (so moving in a diagonal direction is not faster than direct movement)

docs: fix movement vector in examples

---

UnitTests/Source/NetworkObjects/FieldSyncs.cs

Fixes issue # n/a
Changes proposed / reason for pull request:
- All units tests in **NetworkObjectTests** and the first (BlankRpcTest) in **RemoteProcedureCallTests** are failing due to the otherClient field not being cleaned up after **FieldSyncs** tests.
- [ClassCleanup] decorators don't run directly after that class is finished but rather all at once at the end of the test suite because test order isn't guaranteed.
- Therefore, moving the **FieldSyncs** clean up to the [TestCleanup] decorator and the ConnectSetup to [TestInitialize] allows the same unit test logic but allows the remaining unit tests to pass.
Contact me on Discord (Relic) if more info needed.
@BeardedManStudios

Fixed FieldSyncs clean-up to properly clean up before next test class

---

Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Scripts/Multiplayer Menu/MultiplayerMenu.cs

Called `server.Disconnect(true);` on application quit which stops the application from crashing.

RE #139 Fixes issue with crash on Application Quit due to not shutting down the server

---

BeardedManStudios/Source/Forge/Networking/Objects/NetworkObject.cs
UnitTests/Source/NetworkObjects/RemoteProcedureCallTests.cs

Fixes issue # n/a
Changes proposed / reason for pull request
- Added SendRpcUnreliable to allow Rpcs to be sent unreliably
- Made appropriate changes in NetworkObject.cs to reflect this change
- Added a unit test for this
@BeardedManStudios

Added method & unit test for sending Rpcs unreliably

---

README.md

Incredibly minor change to the README to make it point at the new endpoint.

docs: updated getting started link to the new endpoint

---

BeardedManStudios/Source/Forge/Networking/NetWorker.cs
BeardedManStudios/Source/Forge/Networking/SteamP2PServer.cs
BeardedManStudios/Source/Forge/Networking/TCPServer.cs
BeardedManStudios/Source/Forge/Networking/UDPServer.cs

- Added an overload for OnPlayerGuidAssigned to encapsulate checking for if the player was rejected during the handling of the event
- Now SteamP2PServer, TCPServer, and UDPServer will not send any acceptance messages to the client if they were rejected during OnPlayerGuidAssigned handling
This is needed for multiple sockets in order to ensure incoming connections on a secondary socket are from a player connected on the main socket. If a client is rejected when handling OnPlayerGuidAssigned, the server should not accept the client, nor indicate to the client that they were accepted.

Enable player rejection during OnPlayerGuidAssigned

---

BeardedManStudios/BeardedManStudios.csproj
BeardedManStudios/Source/Forge/DataStore/Cache.cs
BeardedManStudios/Source/Forge/Networking/BaseSteamP2P.cs
BeardedManStudios/Source/Forge/Networking/CachedSteamP2PClient.cs
BeardedManStudios/Source/Forge/Networking/NetworkingPlayer.cs
BeardedManStudios/Source/Forge/Networking/Objects/NetworkObject.cs
BeardedManStudios/Source/Forge/Networking/SteamNetworkingPlayer.cs
BeardedManStudios/Source/Forge/Networking/SteamP2PClient.cs
BeardedManStudios/Source/Forge/Networking/SteamP2PPacketComposer.cs
BeardedManStudios/Source/Forge/Networking/SteamP2PServer.cs

Whether the BeardedManStudios project requires Steamworks.dll as a dependency should now be toggleable with the STEAMWORKS conditional compilation symbol in the project settings.
The project compiles both with and without the symbol, and I can confirm the steamless dll will load in unity without the Steamworks.dll present.

Steamworks.dll references toggleable by preprocessor symbol

---

BeardedManStudios/Source/Forge/Networking/NetWorker.cs
BeardedManStudios/Source/Forge/Networking/Objects/NetworkObject.cs
Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Scripts/NetworkManager.cs

Re-coded NetworkManager.SceneReady in order to fix clientside scene network behaviour initialization bugs and also reduce or eliminate race conditions.

Fix issue with scene object initialization

---

BeardedManStudios/Source/Forge/Networking/Websockets.cs

According to RFC 7230, each HTTP header field must end with CRLF, and an additional CRLF is required after the last header-field

Fixing Websockets compliance

---

BeardedManStudios/Source/Forge/Networking/Objects/NetworkObject.cs

This should fix the issue with nestedObjects loading incorrectly for players that just connected to the server, as the parent's networkId will always be lower than his children' networkId.

Nested objects order fix

---

Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Editor/Resources/BMS_Forge_Editor/NetworkManagerTemplate.txt
Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Generated/NetworkManager.cs

Prefab used to have to put the  Instantiation NetworkBehviour  Above other NetworkBehviours it, otherwise cause error.
Now, the order of NetworkBehviour doesn't matter.

Fixed wrong NetworkBehavior Components order cause Network Instantiation error

---

BeardedManStudios/Source/Forge/Networking/NetWorker.cs
Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Editor/Resources/BMS_Forge_Editor/NetworkManagerTemplate.txt

NetWorker/IterateNetworkObjects requested a lock on the Players collection rather than the NetworkObjectList collection, thus invalidated any thread-safety achieved from the lock.
Added comments for Instantiate methods in generated NetworkManager class
Added additional comments to some NetWorker methods

Fixed NetWorker/IterateNetworkObjects lock issue & additional comments

---

ForgeNetworkingUnityEditor/ForgeNetworkingEditor.cs

Related to issue #196, where JSON would be incorrectly outputted in certain cultures. JSON standard assumes point for decimal values rather than a comma.
Remedied by outputting InterpolateValue using CultureInfo.InvariantCulture

Fixed Culture Issue in Interpolation Values

---

Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Scripts/Logging/BMSLogger.cs

Add missing `/` between the `Application.DataPath` and `SAVE_FILE_DIRECTORY_NAME` to put the `Logs` directory in the dataPath.

Fix logFilePath

---

BeardedManStudios/Source/Forge/Networking/TCPClientBase.cs

Make sure that `connectAttemptFailed` uses the same case as other events and matches the `UDPClient`.

Fix capitalisation of connectAttemptFailed event in TCPClientBase to match how it is in UDPClient

---

BeardedManStudios/Source/Forge/Networking/NetWorker.cs

Summary for field `ProximityModeUpdateFrequency` was the same as `ProximityDistance`.
Discord: @PHTV#4632
Please note: I'm not sure what's going on with the indenting as I specifically have set tabs in the editor for this project, but it still seems to not show correctly in the github diff while in editor indenting looks fine in the file.

Update ProximityModeUpdateFrequency documentation.

---

BeardedManStudios/Source/Forge/Networking/Objects/NetworkObject.cs

**Before merging, check if the "if-statements" are truly redundant.**
Seems the events were called in the wrong order leading the new owner to throw the event while IsOwner was still set to false.
Removed the arbitrary if statements and made sure the bool is set before the callbacks are called.
The if statements seem useless because the server is only sending the Rpc to the correct two players. ( See _"AssignOwnership(NetworkingPlayer targetPlayer)"_)
If however you prefer an extra safety check after receiving the rpc, this code should do the trick:
```cs
bool tmpOwner = args.GetNext<bool>();
if (IsOwner != tmpOwner)
{
IsOwner = tmpOwner;
OwnershipChanged();
}
```

Fixed AssignOwnership

---

BeardedManStudios/Source/Forge/Networking/NetWorker.cs
BeardedManStudios/Source/Forge/Networking/UDPClient.cs
BeardedManStudios/Source/Forge/Networking/UDPServer.cs

Fix for issue #136 
In case `Networker.ResolveHost` fails to resolve the provided `host` string then throw an exception and call connectAttemptFailed event handlers for the UDPClient.
Was thinking whether something similar should be added to `UDPServer::NatClientConnectAttempt`? :thinking:  Currently the `return new IPEndPoint(ipAddress, port);` is throwing an `ArgumentNullException` which is not handled there either.
@PHTV#4632

Issue 136 - ipparsing not working correctly

---

Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Editor/Resources/BMS_Forge_Editor/NetworkObjectTemplate.txt
ForgeNetworkingCommon/ForgeNetworkingCommon.csproj
ForgeNetworkingCommon/Templating/ForgeGeneratedField.cs
ForgeNetworkingUnityEditor/ForgeClassObject.cs
ForgeNetworkingUnityEditor/ForgeEditorButton.cs
ForgeNetworkingUnityEditor/ForgeNetworkingEditor.cs
ForgeNetworkingUnityEditor/ForgeNetworkingUnityEditor.csproj
ForgeNetworkingUnityEditor/ValidationResult.cs

Expands validation of fields to the NCW when the user clicks "Save & Compile"
Currently, the NCW populates fields for a given object by using Reflection to retrieve the fields in the class, and performs some filtering based on the name of the field, leaving only the private variables produced by the NCW. This led to issues similar to that described in #152 where fields containing the words "Changed" and "Interpolation" would be produced in the generated code, but on reopening the NCW, these fields would be treated as Changed events or Interpolation variables and be excluded, giving the impression of vanishing variables with no information relayed back to the user as to why this issue was occurring.
This PR modifies this logic to instead have the NCW retrieve fields based on a new …

NCW Improvements to Validation and Logging

---

Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Scripts/NetworkManager.cs

got jittering when the interpolation is updated in FixedUpdate (fixed timestep: 0.01666667), but jittering got removed after I changed the update from FixedUpdate to Update.
a comment on Discord when I asked about this problem:
[emotitron]: I haven't used forge, but if the interpolation lerp is in fixed... That would definitely be in need of correction.

Changed FixedUdpate to Update for smooth interpolation.

---

Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Scripts/MainThreadManager.cs

Currently the actions added through MainThreadManager.Run gets executed only on FixedUpdate.
I think it's better to give users an option to choose where those actions get executed on.
For the backward compatibility, I keep the UpdateType parameter as FixedUpdate.

Improved the MainThreadManager by adding an option to choose where the action gets executed on.

---

BeardedManStudios/Source/Forge/Networking/NetWorker.cs

Fixes Issue
- Machines with multiple active NICs might not be able to find running servers via LAN discovery.
- LAN discovery implementation uses only whatever is the first NIC to search for running servers.
Changes proposed / reason for pull request
- Iterate over all available NICs (limited to WiFi and Ethernet NIC types)
- Search per active NIC per assigned IP for running servers
@BeardedManStudios

Added support for multiple NICs to LAN discovery feature

---

Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Scripts/NetworkManager.cs

After a conversation on discord in #networking-questions a suggestion came up to make the NetworkManager extensible and allow custom code to override current functionality.
Useful in cases where a user would like to show a loading screen while the game scene is loading, but automatic scenes makes that hard. When it is turned off then there are a few gotchas that they need to be aware of with in scene network objects and their correct initialisation.
Also useful when creating scenebased network managers like the showcased work of @k77torpedo where a server can manage multiple scenes.
Changes in this PR based on the suggestions:
- Change all private variables to protected so deriving classes can access them.
- Change all non-generated private methods protected to deriving classes have …

Make NetworkManager extendable

---

Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Editor/Resources/BMS_Forge_Editor/NetworkManagerTemplate.txt
Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Scripts/NetworkManager.cs

Missing changes from previous NetworkManager changes to ensure that the NetworkManager is easily extendable.

Make NetworkManager extendable - missing changes.

---

Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Scripts/NetworkManager.cs

Currently if automatic scenes is turned on on the Network manager then that will trigger as soon as the scene loads with the network manager in it. This causes a null reference exception as the network manager's networker has not been assigned yet via the Initialize method.
The change in this PR adds a flag to indicate whether the Initilaize method has been called or not and will bail out early in the SceneReady method if not preventing the null reference exception.
The reason for this change is questions and suggestions comming up on discord where people would like to keep gameobjects organised. The only reason for a network manager to be a prefab is the automatic scenes functionality attaches the listener in OnEnable. This PR removes this requirement.

Allow in scene network managers to work

---

NatHolePunch/NatHolePunch.cs

When a host disconnects and tries to register again it's details are not updated. The changes in this commit should update the host's details, namely the player variable to allow subsequent nat requests from potential clients to work. This should solve issue #145.

Issue #145 - update host on nat server if it tries to register with same address and port

---

BeardedManStudios/Source/BMSByte.cs

Old method copied the four bytes of the array length into the start of the array and missed the last four bytes of the array.

 Fix BMSByte.GetByteArray

---

Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Editor/Resources/BMS_Forge_Editor/StandAloneNetworkBehaviorTemplate.txt

Standalone NetworkBehaviors only have 4 default RPCs so new RPC byte id count should start from 4 instead of 5.

[BUG] Standalone NetworkBehavior RPC byte ID count missmatch

---

Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Scripts/NetworkManager.cs

Fix for issue #203 
When there are network behaviours place in the scene via the editor (not runtime) then are destroyed during runtime will cause late joining clients to no be able to initialize these and result in gameobjects being stuck in the scene.
This fix looks at the `pendingObjects` list when there are no more scenes to load and if it is not empty then it proceeds to Destroy these objects as they were most probably destroyed already on the server and all other clients.

Issue-203 In scene networkbehaviors error

---

Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Scripts/Networking/Forge/Networking/TCPServer.cs

Probably due to an earlier incorrect merge one of the `WINDOWS_UWP` checks were in the wrong place making the build fail when it is defined.

Fix scripting define check in TCPServer.

---

Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Scripts/Networking/Forge/Networking/NetWorker.cs

Why pushed this PR?
I had a problem that the client A doesn't get synced a network object of the client B sometimes when they try to connect to a server at the same time.
Sequences when new client connects to a server(AFAIK):
1. A client connects to the server.
2. The server sends the data containing currently existed 'NetworkObjects' to the client.
3. A networkObject is created for the client and send the data to other players.
4. On the main thread, the networkObject is initialized and added to 'NetworkObjects'.
In the case that two clients try to connect at the same time,
sometimes the client connected later than another doesn't get the networkObject data for another client.
There are two clients: A, B.
A3-B1-B2-A4 => a networkObject of the client A doesn't get synced on the client B …

Changed the network object registration timing

---

Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Scripts/Networking/Forge/Networking/Objects/NetworkObject.cs

People on discord were asking for a convenience version of SendRpc where instead of one target player they could specify an array of players to send to.

Convenience version of SendRpc to send to a list of NetworkingPlayers.

---

Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Scripts/Networking/ArgumentParser.cs
MasterServer/MasterServer.cs
MasterServer/Program.cs

I've been trying to run the MasterServer.exe as a systemd service on a headless ubuntu vm but I was getting a NullRef:
```[Unit]
Description=Forge Remastered Master Server
After=network.target
[Service]
ExecStart=/usr/bin/mono /opt/MasterServer/MasterServer.exe --port=15940
[Install]
WantedBy=multi-user.target
```
```* master-server.service - Forge Remastered Master Server
Loaded: loaded (/etc/systemd/system/master-server.service; enabled; vendor preset: enabled)
Active: failed (Result: exit-code) since Sat 2019-06-01 15:05:46 UTC; 9min ago
Process: 1370 ExecStart=/usr/bin/mono /opt/MasterServer/MasterServer.exe --port=15940 (code=exited, status=1/FAILURE)
Main PID: 1370 (code=exited, status=1/FAILURE)
Jun 01 15:05:46 unity mono[1370]: (h)elp - Get a full list of commands
Jun 01 15:05:46 …
```

Fixing NullReferenceException in MasterServer.exe when running as a headless service

---

ForgeUnity/Assets/BeardedManStudios/Scripts/Networking/Forge/Networking/Objects/NetworkObject.cs

Opened this in to a new PR, as there was a big change merged in that caused conflicts.
Seems that when calling buffered RPC in server during startup, it resolves to Pending RPC call.
However it seems that when the call is finally delivered, all given parameters are not respected.
https://github.com/BeardedManStudios/ForgeNetworkingRemastered/issues/290

Pending RPC call does not respect all the given parameters

---

ForgeUnity/Assets/BeardedManStudios/Scripts/Networking/Forge/Networking/SteamP2PServer.cs

Change to use the `NetWorker`'s `MaxConnections` as the maximum member count when calling the Steamworks API's `CreateLobby` method instead of it being hard coded to 5.

SteamP2PServer has hardcoded lobby member count for the CreateLobby call

---

ForgeUnity/Assets/BeardedManStudios/Scripts/Networking/Forge/Networking/SteamP2PClient.cs
ForgeUnity/Assets/BeardedManStudios/Scripts/Networking/Forge/Networking/SteamP2PServer.cs

After the recent code cleanup on develop the Steamworks integration has been broken. This PR aims to bring the SteamP2PServer and SteamP2PClient inline with the changes that were made to the UDPServer, UDPClient and Networker classes.

Fix Steamworks integration errors after code cleanup

---

ForgeUnity/Assets/BeardedManStudios/Modules/VOIP/VOIP.cs

I found a small bug when testing VOIP in Forge.
The data allocated in the function to convert byte array to float array is not correct.

Fix buffer overflow in VOIP

---

ForgeUnity/Assets/BeardedManStudios/Editor/Resources/BMS_Forge_Editor/NetworkManagerTemplate.txt
ForgeUnity/Assets/BeardedManStudios/Scripts/NetworkManager.cs

Currently when position/rotation interpolation is on the instantiated object is first spawned at Vector3.zero and then gradually slides (interpolates) to the correct position.
This fix aims to resolve this by disabling the gameobject until instantiation is finalized by Forge.

Fix Object instantiated at Vector3.zero and then slide to position when interpolation is on

---

ForgeUnity/Assets/BeardedManStudios/Scripts/Networking/BMSByte.cs

Should be `isn't` instead of `is`.
Unless this makes sense `Exception: The type UnityEngine.Vector3 is getable from basic type, maybe try one of the other getters?`

BMSByte exception typo

---

ForgeUnity/Assets/BeardedManStudios/Editor/Resources/BMS_Forge_Editor/NetworkBehaviorTemplate.txt
ForgeUnity/Assets/BeardedManStudios/Editor/Resources/BMS_Forge_Editor/NetworkManagerTemplate.txt

Client side fix for objects being spawned at 0,0,0 before warping to their proper starting location.

Update NetworkBehaviorTemplate.txt to prevent objects from existing at 0,0,0 client side before warping to their initial location

---

ForgeUnity/Assets/BeardedManStudios/Scripts/Logging/BMSLogger.cs

Noticed that BMSLogger uses rich text tags to colorize Debug/Warning/Error logs differently, but the OnGUI call wasn't using a richtext style so the tags were being printed unparsed.
Fixed that and also made a small cleanup by use string interpolation instead of string.Format

Richtext BMSLogger fix

---

ForgeUnity/Assets/BeardedManStudios/Scripts/Networking/Forge/Networking/NetworkInterfaceAccumulator.cs

The returned interfaces are all invalid/unknown because we don't have the rights to get the interfaces "states".
We know for our Android devices the names are either "lo" for "localhost" or "wlan0" for "wifi". Basically, the OperationalStatus will be Unknown, because you do not have the rights. But for safety, we still consider the other "valid" cases to be used.

[Fix] Android LAN Network Discovery

---

ForgeUnity/Assets/BeardedManStudios/Editor/Resources/BMS_Forge_Editor/NetworkBehaviorTemplate.txt
ForgeUnity/Assets/BeardedManStudios/Examples/SceneUnloading/Scripts/SomeNetworkObject.cs
ForgeUnity/Assets/BeardedManStudios/Scripts/NetworkBehavior.cs
ForgeUnity/Assets/BeardedManStudios/Scripts/Networking/Forge/Networking/Objects/NetworkObject.cs

An example of this is in the SomeNetworkObject.cs used for additive scenes
There is a new function which you can override in a NetworkBehaviour called RegisterCustomRPCs(NetworkObject)
This is called before NetworkStart so the behaviour.networkObject will still be null at this time
hence why it has a argument NetworkObject which is a valid NetworkObject
Inside the RegisterCustomRPCs
you can register RPCs like you normally would except you have can register the RPC and you'll get the id back
for example
`
private byte RPC_SERVER_TEST_RPC;
protected override void RegisterCustomRPCs(NetworkObject networkObject)
{
base.RegisterCustomRPCs(networkObject);
RPC_SERVER_TEST_RPC = networkObject.RegisterRpc("ServerTestRPC", ServerTestRPC, typeof(int), typeof(string));
}
`
then like then you can use …

Added the option to register rpc using the same approach as the NCW

---

README.md

Remove misleading reference to old nightly builds as they no longer work due to shipping with source instead of compiled dlls.

Remove build section from README

---

ForgeUnity/Assets/BeardedManStudios/Scripts/MainThreadManager.cs

When Unity's experimental Configurable Enter Play Mode (https://docs.unity3d.com/2019.3/Documentation/Manual/ConfigurableEnterPlayMode.html) is enabled static fields are not reinitialized to null.
This change makes Forge compatible with Configurable Enter Play Mode by clearing the static singleton _instance field when the MainThreadManager is destroyed on exiting play mode.
Replaces https://github.com/BeardedManStudios/ForgeNetworkingRemastered/pull/365 which was incorrectly targeted at master branch.

Fix for Unity's Configurable Enter Play Mode

---

.gitignore
ForgeAlloy/ForgeAlloyUnity/Assets/ForgeNetworking/Networking/Players/ForgePlayerTimeoutBridge.cs

The _timedOutPlayers should be cleared after they have been removed from the PlayerRepository

Clear _timedOutPlayers
