BeardedManStudios/ForgeNetworkingRemastered

- Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Scenes/Lobby.unity
- Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/WIP/Modules/LobbySystem/StartGame.cs
- Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/WIP/Modules/Prefabs/Start Game.prefab
Here is the File changes to Lobby, last pull request I made was the Lobby Documentation, This is the files for the Lobby Docs. 
Enjoy the Lobby!!!
Discord username:
NuclearRasberry
> Lobby Finish up

- ForgeNetworkingUnityEditor/ForgeNetworkingEditor.cs
The FNR wizard tries to access to old paths and it's broken when you change the route of the project.
> Fixed  problems when you change the route of the project.

- MasterServer/Program.cs
> Missing custom host ip

- BeardedManStudios/Source/BMSByte.cs
- UnitTests/Source/BMSByteTests.cs
Not entirely sure how bmsbyte works so I dont know if those break something or not but it's faster 👍 .
> GetArray optimization 40ms -> 26ms

- BeardedManStudios/Source/Forge/Networking/Objects/NetworkObject.cs
Fixed ownershipChanged event not called on the new owner.
> Fixed ownershipChanged event

- docs/GettingStarted/basic-moving-cube-example/index.html
http://docs.forgepowered.com/GettingStarted/basic-moving-cube-example/
https://github.com/BeardedManStudios/ForgeNetworkingRemastered/issues/128
> Fixed missed comma in docs;

- Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Scripts/NetworkManager.cs
- Fixes sending proper number of players on server
- Changes way in which updates are send:
We don't have to connect to master server again because in normal operation host will be connected to master server at all times. We need to simply send update and if error occurs then disconnect from master server.
> Fixes improper way of sending updates to master server

- docs/mkdocs/docs/NetworkObject/RemoteProcedureCalls/rpc-validation-by-server.md
It is now more clear what the developer needs to do when getting started with server validation of RPCs.
> Improved example for easier understanding

- Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Editor/Resources/BMS_Forge_Editor/NetworkManagerTemplate.txt
- Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Generated/NetworkManager.cs
the same thing is called just a few lines above, no reason to do it twice (?)
> remove redundant metadata clear

- Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Generated/UserGenerated/ChatManagerBehavior.cs
- Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Generated/UserGenerated/CubeForgeGameBehavior.cs
- Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Generated/UserGenerated/ExampleProximityPlayerBehavior.cs
- Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Generated/UserGenerated/NetworkCameraBehavior.cs
- Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Generated/UserGenerated/TestBehavior.cs
- Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Scripts/NetworkManager.cs
> Fixed nested ProcessOthers issue in NetworkManager and default UserGenerated code

- BeardedManStudios/Source/Forge/Networking/UDPPacketComposer.cs
Moved the sending of unreliable RPC packets onto the write thread so the `thread.sleep()` doesn't sleep the main thread.
> Send unreliable packets on the write thread

- .gitignore
- BeardedManStudios/Source/Forge/Networking/CommonServer.cs
- BeardedManStudios/Source/Forge/Networking/UDPClient.cs
- BeardedManStudios/Source/Forge/Networking/UDPGroupIds.cs
- BeardedManStudios/Source/Forge/Networking/UDPServer.cs
Possible fix for issues #141 and #211 where connected clients get disconnected if max connections is reached on a new client connection. _(More info on #211 )_
The fix will potentially need to be added to the TCPServer and TCPClient code too.
> Fix for issues 141 and 211

- .editorconfig
- CONTRIBUTING.md
Add .editorconfig to help standardize and enforce coding standards for all contributions.
> [enhancement] Add .editorconfig

- BeardedManStudios/Source/Forge/Networking/IUserAuthenticator.cs
- BeardedManStudios/Source/Forge/Networking/NetWorker.cs
- BeardedManStudios/Source/Forge/Networking/SteamP2PClient.cs
- BeardedManStudios/Source/Forge/Networking/SteamP2PServer.cs
- BeardedManStudios/Source/Forge/Networking/TCPClientBase.cs
- BeardedManStudios/Source/Forge/Networking/TCPServer.cs
- BeardedManStudios/Source/Forge/Networking/UDPClient.cs
- BeardedManStudios/Source/Forge/Networking/UDPServer.cs
- Converted the IUserAuthenticator to use callbacks instead of returning to better support authenticators like Steam
> Convert IUserAuthenticator to use callbacks

- create-zip-as-assets-package.sh
As the title says, a script to automate the process. It's written for bash. So Windows users will need to have this installed (Git for Windows, Cygwin, ...). I've only tested it on Windows but I think it should work on macOS and Linux as well.
> Added shell script (bash) to automate the process of using Forge Networking from sources

- Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Editor/Resources/BMS_Forge_Editor/NetworkManagerTemplate.txt
Added a small check to see if the network object prefab exists.
> Added error message for missing network prefabs

- Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Editor/Resources/BMS_Forge_Editor/NetworkBehaviorTemplate.txt
Changes are from Brett, just making sure that they are not lost on Discord.
> Clean up transform code in NetworkBehavior template

- Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Scripts/NetworkManager.cs
Adds the proposed changes from #203
> Further improvements based on comment in Issue #203

- Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Scripts/Networking/Forge/Networking/Objects/NetworkObject.cs
The solution to the error described in issue-274
> issue-274 - InvalidCastException when connection through Steam

- Forge Networking Remastered Unity/Assets/Bearded Man Studios Inc/Scripts/NetworkManager.cs
This was a regression after changing the foreach to iterate over a list instead of a dictionary
> Fix issue with incorrectly accessing the foreach loop iteration variable

- ForgeUnity/Assets/BeardedManStudios/Scripts/Multiplayer Menu/JoinMenu.cs
Also fixed a bug with calling AddServer outside of main thread
> RefreshMasterServerListings was not fully implemented

- ForgeUnity/Assets/BeardedManStudios/Editor/ForgeExtensions.cs
- ForgeUnity/Assets/BeardedManStudios/Editor/ForgeNetworkingEditor.cs
Adding perforce checkout support.
Adding safety for locking editor assemblies.
> Perforce Support and Editor Locking Files Fix

- BeardedManStudios/BeardedManStudios.csproj
- updated source relative paths to point to ForgeUnity
- set explicit language version
> Standalone project compilation fixes

- ForgeAlloy/ForgeAlloyUnity/Assets/ForgeNetworking/Networking/ForgeNetworkMediator.cs
- ForgeAlloy/ForgeAlloyUnity/Assets/ForgeNetworking/Networking/INetworkFacade.cs
- ForgeAlloy/ForgeAlloyUnity/Assets/ForgeNetworking/Networking/Messaging/ForgeMessageBus.cs
Noticed a todo in the code, does this seem like a cleaner way of checking whether to interpret a message? I made `IsServer` and `IsClient` properties on INetworkFacade.
> Check if INetworkFacade is server or client

- ForgeAlloy/ForgeAlloyUnity/Assets/ForgeNetworking/DataStructures/ForgeSignature.cs
- ForgeAlloy/ForgeAlloyUnity/Assets/ForgeNetworking/DataStructures/ForgeSignatureIdGenerator.cs
- ForgeAlloy/ForgeAlloyUnity/Assets/ForgeNetworking/DataStructures/ForgeSignatureIdGenerator.cs.meta
- ForgeAlloy/ForgeAlloyUnity/Assets/ForgeNetworking/DataStructures/ISignatureGenerator.cs
- ForgeAlloy/ForgeAlloyUnity/Assets/ForgeNetworking/DataStructures/ISignatureGenerator.cs.meta
- ForgeAlloy/ForgeAlloyUnity/Assets/ForgeNetworking/Factory/ForgeNetworkingTypeFactory.cs
- ForgeAlloy/ForgeAlloyUnity/Assets/ForgeNetworking/Networking/Messaging/ForgeMessageReceipt.cs
- ForgeAlloy/ForgeAlloyUnity/Assets/ForgeNetworking/Networking/Players/ForgePlayerSignature.cs
- ForgeAlloy/ForgeAlloyUnity/Assets/ForgeNetworking/Scenes/MultiplayerMenu.unity
This PR is coming from an observation from @k77torpedo on Discord about how a static `int` with a lock is being used. Now is a good time to hop in and fix it since it is a relatively easy fix.
> Removing static integer and using atomic

- ForgeAlloy/ForgeAlloyUnity/Assets/Examples/Chat/src/Messages/Interpreters/ChatInterpreter.cs
- ForgeAlloy/ForgeAlloyUnity/Assets/ForgeNetworking/Editor/src/UI/Windows/ContributingWindow.cs
- ForgeAlloy/ForgeAlloyUnity/Assets/ForgeNetworking/Networking/MessageExtensions.cs
- ForgeAlloy/ForgeAlloyUnity/Assets/ForgeNetworking/Networking/SocketNotServerException.cs
This will make it easier for developers to forward a client's message to all other connected clients (excluding the sender).
> Adding message forward extension for server

- ForgeAlloy/ForgeAlloyUnity/Assets/Examples/Chat/Scenes/Chat.unity
- ForgeAlloy/ForgeAlloyUnity/Assets/Examples/Chat/src/DisconnectButton.cs
- ForgeAlloy/ForgeAlloyUnity/Assets/Examples/Chat/src/DisconnectButton.cs.meta
- ForgeAlloy/ForgeAlloyUnity/Assets/Examples/ComplexSample/src/Network/ComplexSampleNetwork.cs
- ForgeAlloy/ForgeAlloyUnity/Assets/ForgeNetworking/Factory/AbstractFactory.cs
- ForgeAlloy/ForgeAlloyUnity/Assets/ForgeNetworking/ForgeRegistration.cs
- ForgeAlloy/ForgeAlloyUnity/Assets/ForgeNetworking/Scenes/MultiplayerMenu.unity
- ForgeAlloy/ForgeAlloyUnity/Assets/ForgeNetworking/src/Engine/ForgeEngineFacade.cs
- ForgeAlloy/ForgeAlloyUnity/Assets/ForgeNetworking/src/Engine/ForgeRegistrations.cs
- ForgeAlloy/ForgeAlloyUnity/Assets/ForgeNetworking/src/Engine/IEngineFacade.cs
Adding disconnect button to chat example as well:
> Setting up a way to disconnect using the engine to make it easier
